### PR TITLE
Feature/add chart museum action

### PR DESCRIPTION
**Pull request by jaydenrasmussen**
This PR moves us away from using github pages to host our charts, and allows us to take advantage of [chartmuseum](https://github.com/helm/chartmuseum) for our helm charts. This will allow us to also make the repo private instead of a public repo to take advantage of self-hosted runners.

For more info on the projects involved here see the following links
[Helm Push](https://github.com/chartmuseum/helm-push)
[Chartmuseum](https://github.com/helm/chartmuseum)

### CODE REVIEW

**Comment by jaydenrasmussen** [comment]
> So do we still need to increment the version manually? Or if the version stays the same then it will override the previous chart?

Chartmuseum won't allow us to overwrite charts (it's a security feature), so we'll need to manually bump versions for now, but the [Helm Push](https://github.com/chartmuseum/helm-push) plugin does allow us to manually set a version, so we could set it so all of our charts follow the same versioning that comes from a git tag instead of a manual bump in the Chart.yml

**Comment by paraplexed** [comment]
What's our plan for moving everyone over to this? Right now the chart url is hardcoded in everyone's github actions.

**Comment by fuzzybaird** [comment]
@jaydenrasmussen Yah, the tag is tricky, because there is only 1 repo -> MANY -> charts. So the versioning falls apart with tags, because each of them could be at a different state. But I am totally fine with manual for now.

**Comment by jaydenrasmussen** [comment]
> What's our plan for moving everyone over to this? Right now the chart url is hardcoded in everyone's github actions.

@paraplexed 
I think we need to discuss options here but, initially I would think a communication in the Architecture channel with a day for deprecation date to move the repo over to private a long with the specific commands that need to change should be enough to get this through. As far as I can tell, we only need to have them change how they add their helm repo. `helm repo add chg https://chartmuseum.shared.aws.chgit.com`

**Comment by paraplexed** [comment]
@jaydenrasmussen now that master is on 1.4, I think now is a good time to merge this. For anyone wanting the bleeding edge we can tell them to update their helm upgrade command, and everyone else can do it over the course of the next month or so when they have time. What do you think of that?

**Pull request merged**
