### PR TITLE
feat: add CronJob to the service chart

### PR DESCRIPTION
**Pull request by cuporter**
This adds cronjob to the service template. On LTC we want to use this to hit our services every few minutes so we can fire an alert if the service cannot be reached. This will catch things like a problem with our Istio setup, authentication issues, expired SSL certs, etc.

### CODE REVIEW

**Review by paraplexed — APPROVED** [review]
This looks good -- Can you add a commented out example into the `charts/service/values.yaml` file?

**Comment by paraplexed** [comment]
Also, were you able to test this out locally? It's pretty easy to miss small syntax problems in a code review with these, but the logic all seems right to me.

**Comment by cuporter** [comment]
> 
> 
> Also, were you able to test this out locally? It's pretty easy to miss small syntax problems in a code review with these, but the logic all seems right to me.

Yes, I tested it locally. The only odd behavior I've seen from it is if the job fails it continues to retry no matter what I set the retryPolicy to. If I set the restartPolicy to OnFailure then it replaces the job that failed with a new attempt, and if I set retryPolicy to Never then it creates a new job. If you have any suggestions there, I'm interested. Leaving it set to OnFailure yields reasonable behavior since it pretty quickly goes to CrashLoopBackoff so it isn't restarting all that frequently, but it's not perfect behavior.

**Comment by paraplexed** [comment]
> 
> 
> > Also, were you able to test this out locally? It's pretty easy to miss small syntax problems in a code review with these, but the logic all seems right to me.
> 
> Yes, I tested it locally. The only odd behavior I've seen from it is if the job fails it continues to retry no matter what I set the retryPolicy to. If I set the restartPolicy to OnFailure then it replaces the job that failed with a new attempt, and if I set retryPolicy to Never then it creates a new job. If you have any suggestions there, I'm interested. Leaving it set to OnFailure yields reasonable behavior since it pretty quickly goes to CrashLoopBackoff so it isn't restarting all that frequently, but it's not perfect behavior.

I believe that's because of how the CronJob Controller in Kubernetes works. The controller is looking for a certain number of successful runs from the cronjob in a given time period (ie your schedule), if it hasn't had one, it will attempt to schedule the job to run again. This is why it's recommended to do cronjobs that are idempotent.

Depending on what your cronjob does, it might make sense to only exit the job with a failed status code if you want to immediately retry the run of it. For example instead of doing a `process.exit(1)`, you would log something out for kibana to alert on, and do a `process.exit(0)`, and let the schedule dictate the next time a run is attempted.

**Review by paraplexed — APPROVED** [review]

**Review by faradayfan — APPROVED** [review]
Nice!

**Comment by faradayfan** [comment]
> > Also, were you able to test this out locally? It's pretty easy to miss small syntax problems in a code review with these, but the logic all seems right to me.
> 
> Yes, I tested it locally. The only odd behavior I've seen from it is if the job fails it continues to retry no matter what I set the retryPolicy to. If I set the restartPolicy to OnFailure then it replaces the job that failed with a new attempt, and if I set retryPolicy to Never then it creates a new job. If you have any suggestions there, I'm interested. Leaving it set to OnFailure yields reasonable behavior since it pretty quickly goes to CrashLoopBackoff so it isn't restarting all that frequently, but it's not perfect behavior.

I think if the

**Pull request merged**
